// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACucd91hp-WQ4yID9cdGBkZT9bg3vyVRk',
    appId: '1:370664596706:web:758f2d87202270ba1eeabb',
    messagingSenderId: '370664596706',
    projectId: 'blood--app-22b4a',
    authDomain: 'blood--app-22b4a.firebaseapp.com',
    databaseURL: 'https://blood--app-22b4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood--app-22b4a.firebasestorage.app',
    measurementId: 'G-BY3H939KCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0I8xRZN9S-oVTlDEcgWq87OiJV3oCAKM',
    appId: '1:370664596706:android:6db03e1d9ed3824e1eeabb',
    messagingSenderId: '370664596706',
    projectId: 'blood--app-22b4a',
    databaseURL: 'https://blood--app-22b4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood--app-22b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKG6yQHlSDuqKBzCprKwvxlgESMkiH_4',
    appId: '1:370664596706:ios:180e93e83cbd57431eeabb',
    messagingSenderId: '370664596706',
    projectId: 'blood--app-22b4a',
    databaseURL: 'https://blood--app-22b4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood--app-22b4a.firebasestorage.app',
    iosBundleId: 'com.example.bloodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKG6yQHlSDuqKBzCprKwvxlgESMkiH_4',
    appId: '1:370664596706:ios:180e93e83cbd57431eeabb',
    messagingSenderId: '370664596706',
    projectId: 'blood--app-22b4a',
    databaseURL: 'https://blood--app-22b4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood--app-22b4a.firebasestorage.app',
    iosBundleId: 'com.example.bloodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACucd91hp-WQ4yID9cdGBkZT9bg3vyVRk',
    appId: '1:370664596706:web:00367d737650b6e01eeabb',
    messagingSenderId: '370664596706',
    projectId: 'blood--app-22b4a',
    authDomain: 'blood--app-22b4a.firebaseapp.com',
    databaseURL: 'https://blood--app-22b4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blood--app-22b4a.firebasestorage.app',
    measurementId: 'G-C44L4YXMQC',
  );
}
